name: Release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+a[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+b[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+rc[0-9]+"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - name: Install poetry
        run: pipx install poetry
      - name: Set up python
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d
        with:
          python-version: "3.10"
          cache: poetry
      - name: Build with poetry
        run: poetry build
      - name: Upload build artifacts
        uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b
        with:
          path: ./dist
  create-draft-release:
    name: Create draft release
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: write
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e
      - name: Identify prerelease
        id: identify-prerelease
        run: |
          flag=""
          if [[ ! ${{ github.ref_name }} =~ ^refs/tags/[0-9]+.[0-9]+.[0-9]+$ ]]
          then
            flag=" --prerelease"
          fi
          echo "PRERELEASE=$flag" >> $GITHUB_OUTPUT
      - name: Create draft release
        run: >
          gh release create --draft${{ steps.identify-prerelease.outputs.PRERELEASE }}
          --repo ${{ github.repository }}
          ${{ github.ref_name }}
          artifact/*
        env:
          GH_TOKEN: ${{ github.token }}
